spring:
  application:
    name: Buy-Baazar
  profiles:
    active: dev # Change this to 'prod' for Render deployment
  jackson:
    # Fail on unknown properties during deserialization
    deserialization:
      fail-on-unknown-properties: false
    # Other common settings
    serialization:
      fail-on-empty-beans: false


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.mail: DEBUG
    org.springframework.boot.autoconfigure.mail: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG